apiVersion: v2
name: rpe-pdf-service
home: https://github.com/hmcts/rpe-pdf-service
version: 0.6.15
description: PDF generation service
maintainers:
  - name: HMCTS Platform engineering team
dependencies:
  - name: java
    version: 4.0.1
    repository: '@hmctspublic'
