java:
  applicationPort: 5500
  aadIdentityName: rpe
  ingressHost: rpe-pdf-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
    LOGBACK_REQUIRE_ALERT_LEVEL: 'false'
    LOGBACK_REQUIRE_ERROR_CODE: 'false'
  image: 'hmctspublic.azurecr.io/rpe/pdf-service:latest'
  keyVaults:
    "rpe-shared":
      secrets:
        - AppInsightsInstrumentationKey
